Repository SaiSVemula/HobbiesConnect, pull requests merged in 2025-01, with the labels that each got.

#17 Authentication
  api/forms.py
  api/templates/login.html
  api/views.py
  db.sqlite3
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/components/FriendRequests/DeleteRequest.vue
  frontend/src/components/Header.vue
  frontend/src/components/Profile/AddHobby.vue
  frontend/src/components/Profile/DeleteHobby.vue
  frontend/src/components/Profile/UpdatePassword.vue
  frontend/src/components/Profile/UpdateProfile.vue
  frontend/src/data/data.ts
  frontend/src/main.ts
  frontend/src/router/index.ts
  frontend/src/utils/auth.ts
  frontend/src/utils/csrf.ts
  project/settings.py
  project/urls.py
  requirements.txt
Labels: bug

#16 Update README.md
  README.md
Labels: documentation

#20 Find friends
  README.md
  api/models.py
  api/urls.py
  api/utils.py
  api/views.py
  db.sqlite3
  frontend/src/App.vue
  frontend/src/components/AddFriend.vue
  frontend/src/components/FindFriends/AddFriend.vue
  frontend/src/components/FindFriends/Filter.vue
  frontend/src/components/FindFriends/Friend.vue
  frontend/src/components/FindFriends/Pagination.vue
  frontend/src/components/Friend.vue
  frontend/src/components/FriendRequests/DeleteRequest.vue
  frontend/src/components/FriendRequests/Request.vue
  frontend/src/components/Header.vue
  frontend/src/components/Profile/AddHobby.vue
  frontend/src/components/Profile/DeleteHobby.vue
  frontend/src/components/Profile/HobbyList.vue
  frontend/src/components/Profile/UpdatePassword.vue
  frontend/src/components/Profile/UpdateProfile.vue
  frontend/src/data/data.ts
  frontend/src/pages/FindFriends.vue
  frontend/src/pages/FriendRequests.vue
  frontend/src/router/index.ts
  frontend/src/utils/auth.ts
  frontend/src/utils/csrf.ts
  frontend/src/utils/interfaces.ts
  project/settings.py
Labels: enhancement
